/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ApiVisionExtractRouteImport } from './routes/api/vision.extract'
import { Route as ApiSessionExportRouteImport } from './routes/api/session.export'
import { Route as ApiGrievanceDraftRouteImport } from './routes/api/grievance.draft'
import { Route as ApiBhashiniAsrRouteImport } from './routes/api/bhashini.asr'
import { Route as ApiAgentTurnRouteImport } from './routes/api/agent.turn'
import { Route as ApiAgentStreamRouteImport } from './routes/api/agent.stream'
import { Route as ApiAgentResumeRouteImport } from './routes/api/agent.resume'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVisionExtractRoute = ApiVisionExtractRouteImport.update({
  id: '/api/vision/extract',
  path: '/api/vision/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionExportRoute = ApiSessionExportRouteImport.update({
  id: '/api/session/export',
  path: '/api/session/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrievanceDraftRoute = ApiGrievanceDraftRouteImport.update({
  id: '/api/grievance/draft',
  path: '/api/grievance/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBhashiniAsrRoute = ApiBhashiniAsrRouteImport.update({
  id: '/api/bhashini/asr',
  path: '/api/bhashini/asr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTurnRoute = ApiAgentTurnRouteImport.update({
  id: '/api/agent/turn',
  path: '/api/agent/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent/stream',
  path: '/api/agent/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentResumeRoute = ApiAgentResumeRouteImport.update({
  id: '/api/agent/resume',
  path: '/api/agent/resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/agent/resume': typeof ApiAgentResumeRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/bhashini/asr': typeof ApiBhashiniAsrRoute
  '/api/grievance/draft': typeof ApiGrievanceDraftRoute
  '/api/session/export': typeof ApiSessionExportRoute
  '/api/vision/extract': typeof ApiVisionExtractRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/agent/resume': typeof ApiAgentResumeRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/bhashini/asr': typeof ApiBhashiniAsrRoute
  '/api/grievance/draft': typeof ApiGrievanceDraftRoute
  '/api/session/export': typeof ApiSessionExportRoute
  '/api/vision/extract': typeof ApiVisionExtractRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/agent/resume': typeof ApiAgentResumeRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/bhashini/asr': typeof ApiBhashiniAsrRoute
  '/api/grievance/draft': typeof ApiGrievanceDraftRoute
  '/api/session/export': typeof ApiSessionExportRoute
  '/api/vision/extract': typeof ApiVisionExtractRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/templates'
    | '/api/agent/resume'
    | '/api/agent/stream'
    | '/api/agent/turn'
    | '/api/bhashini/asr'
    | '/api/grievance/draft'
    | '/api/session/export'
    | '/api/vision/extract'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/api/templates'
    | '/api/agent/resume'
    | '/api/agent/stream'
    | '/api/agent/turn'
    | '/api/bhashini/asr'
    | '/api/grievance/draft'
    | '/api/session/export'
    | '/api/vision/extract'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/templates'
    | '/api/agent/resume'
    | '/api/agent/stream'
    | '/api/agent/turn'
    | '/api/bhashini/asr'
    | '/api/grievance/draft'
    | '/api/session/export'
    | '/api/vision/extract'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  ApiAgentResumeRoute: typeof ApiAgentResumeRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
  ApiAgentTurnRoute: typeof ApiAgentTurnRoute
  ApiBhashiniAsrRoute: typeof ApiBhashiniAsrRoute
  ApiGrievanceDraftRoute: typeof ApiGrievanceDraftRoute
  ApiSessionExportRoute: typeof ApiSessionExportRoute
  ApiVisionExtractRoute: typeof ApiVisionExtractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/vision/extract': {
      id: '/api/vision/extract'
      path: '/api/vision/extract'
      fullPath: '/api/vision/extract'
      preLoaderRoute: typeof ApiVisionExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/export': {
      id: '/api/session/export'
      path: '/api/session/export'
      fullPath: '/api/session/export'
      preLoaderRoute: typeof ApiSessionExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grievance/draft': {
      id: '/api/grievance/draft'
      path: '/api/grievance/draft'
      fullPath: '/api/grievance/draft'
      preLoaderRoute: typeof ApiGrievanceDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bhashini/asr': {
      id: '/api/bhashini/asr'
      path: '/api/bhashini/asr'
      fullPath: '/api/bhashini/asr'
      preLoaderRoute: typeof ApiBhashiniAsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/turn': {
      id: '/api/agent/turn'
      path: '/api/agent/turn'
      fullPath: '/api/agent/turn'
      preLoaderRoute: typeof ApiAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stream': {
      id: '/api/agent/stream'
      path: '/api/agent/stream'
      fullPath: '/api/agent/stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/resume': {
      id: '/api/agent/resume'
      path: '/api/agent/resume'
      fullPath: '/api/agent/resume'
      preLoaderRoute: typeof ApiAgentResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  ApiAgentResumeRoute: ApiAgentResumeRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
  ApiAgentTurnRoute: ApiAgentTurnRoute,
  ApiBhashiniAsrRoute: ApiBhashiniAsrRoute,
  ApiGrievanceDraftRoute: ApiGrievanceDraftRoute,
  ApiSessionExportRoute: ApiSessionExportRoute,
  ApiVisionExtractRoute: ApiVisionExtractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
