/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTemplatesRouteImport } from './routes/api/templates'
import { Route as ApiSamplesRouteImport } from './routes/api/samples'
import { Route as AuthenticatedSchemesRouteImport } from './routes/_authenticated/schemes'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHouseholdRouteImport } from './routes/_authenticated/household'
import { Route as AuthenticatedGrievancesRouteImport } from './routes/_authenticated/grievances'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiVisionExtractRouteImport } from './routes/api/vision.extract'
import { Route as ApiSessionExportRouteImport } from './routes/api/session.export'
import { Route as ApiGrievanceDraftRouteImport } from './routes/api/grievance.draft'
import { Route as ApiBhashiniAsrRouteImport } from './routes/api/bhashini.asr'
import { Route as ApiAgentTurnRouteImport } from './routes/api/agent.turn'
import { Route as ApiAgentStreamRouteImport } from './routes/api/agent.stream'
import { Route as ApiAgentResumeRouteImport } from './routes/api/agent.resume'

const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTemplatesRoute = ApiTemplatesRouteImport.update({
  id: '/api/templates',
  path: '/api/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSamplesRoute = ApiSamplesRouteImport.update({
  id: '/api/samples',
  path: '/api/samples',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSchemesRoute = AuthenticatedSchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHouseholdRoute = AuthenticatedHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGrievancesRoute = AuthenticatedGrievancesRouteImport.update({
  id: '/grievances',
  path: '/grievances',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiVisionExtractRoute = ApiVisionExtractRouteImport.update({
  id: '/api/vision/extract',
  path: '/api/vision/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionExportRoute = ApiSessionExportRouteImport.update({
  id: '/api/session/export',
  path: '/api/session/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGrievanceDraftRoute = ApiGrievanceDraftRouteImport.update({
  id: '/api/grievance/draft',
  path: '/api/grievance/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBhashiniAsrRoute = ApiBhashiniAsrRouteImport.update({
  id: '/api/bhashini/asr',
  path: '/api/bhashini/asr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentTurnRoute = ApiAgentTurnRouteImport.update({
  id: '/api/agent/turn',
  path: '/api/agent/turn',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentStreamRoute = ApiAgentStreamRouteImport.update({
  id: '/api/agent/stream',
  path: '/api/agent/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentResumeRoute = ApiAgentResumeRouteImport.update({
  id: '/api/agent/resume',
  path: '/api/agent/resume',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/impact': typeof ImpactRoute
  '/kiosk': typeof KioskRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grievances': typeof AuthenticatedGrievancesRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/api/samples': typeof ApiSamplesRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/agent/resume': typeof ApiAgentResumeRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/bhashini/asr': typeof ApiBhashiniAsrRoute
  '/api/grievance/draft': typeof ApiGrievanceDraftRoute
  '/api/session/export': typeof ApiSessionExportRoute
  '/api/vision/extract': typeof ApiVisionExtractRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/impact': typeof ImpactRoute
  '/kiosk': typeof KioskRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/grievances': typeof AuthenticatedGrievancesRoute
  '/household': typeof AuthenticatedHouseholdRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/schemes': typeof AuthenticatedSchemesRoute
  '/api/samples': typeof ApiSamplesRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/agent/resume': typeof ApiAgentResumeRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/bhashini/asr': typeof ApiBhashiniAsrRoute
  '/api/grievance/draft': typeof ApiGrievanceDraftRoute
  '/api/session/export': typeof ApiSessionExportRoute
  '/api/vision/extract': typeof ApiVisionExtractRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/app': typeof AppRoute
  '/auth': typeof AuthRoute
  '/impact': typeof ImpactRoute
  '/kiosk': typeof KioskRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/grievances': typeof AuthenticatedGrievancesRoute
  '/_authenticated/household': typeof AuthenticatedHouseholdRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/schemes': typeof AuthenticatedSchemesRoute
  '/api/samples': typeof ApiSamplesRoute
  '/api/templates': typeof ApiTemplatesRoute
  '/api/agent/resume': typeof ApiAgentResumeRoute
  '/api/agent/stream': typeof ApiAgentStreamRoute
  '/api/agent/turn': typeof ApiAgentTurnRoute
  '/api/bhashini/asr': typeof ApiBhashiniAsrRoute
  '/api/grievance/draft': typeof ApiGrievanceDraftRoute
  '/api/session/export': typeof ApiSessionExportRoute
  '/api/vision/extract': typeof ApiVisionExtractRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/impact'
    | '/kiosk'
    | '/admin'
    | '/dashboard'
    | '/grievances'
    | '/household'
    | '/profile'
    | '/schemes'
    | '/api/samples'
    | '/api/templates'
    | '/api/agent/resume'
    | '/api/agent/stream'
    | '/api/agent/turn'
    | '/api/bhashini/asr'
    | '/api/grievance/draft'
    | '/api/session/export'
    | '/api/vision/extract'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/auth'
    | '/impact'
    | '/kiosk'
    | '/admin'
    | '/dashboard'
    | '/grievances'
    | '/household'
    | '/profile'
    | '/schemes'
    | '/api/samples'
    | '/api/templates'
    | '/api/agent/resume'
    | '/api/agent/stream'
    | '/api/agent/turn'
    | '/api/bhashini/asr'
    | '/api/grievance/draft'
    | '/api/session/export'
    | '/api/vision/extract'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/app'
    | '/auth'
    | '/impact'
    | '/kiosk'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/grievances'
    | '/_authenticated/household'
    | '/_authenticated/profile'
    | '/_authenticated/schemes'
    | '/api/samples'
    | '/api/templates'
    | '/api/agent/resume'
    | '/api/agent/stream'
    | '/api/agent/turn'
    | '/api/bhashini/asr'
    | '/api/grievance/draft'
    | '/api/session/export'
    | '/api/vision/extract'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AppRoute: typeof AppRoute
  AuthRoute: typeof AuthRoute
  ImpactRoute: typeof ImpactRoute
  KioskRoute: typeof KioskRoute
  ApiSamplesRoute: typeof ApiSamplesRoute
  ApiTemplatesRoute: typeof ApiTemplatesRoute
  ApiAgentResumeRoute: typeof ApiAgentResumeRoute
  ApiAgentStreamRoute: typeof ApiAgentStreamRoute
  ApiAgentTurnRoute: typeof ApiAgentTurnRoute
  ApiBhashiniAsrRoute: typeof ApiBhashiniAsrRoute
  ApiGrievanceDraftRoute: typeof ApiGrievanceDraftRoute
  ApiSessionExportRoute: typeof ApiSessionExportRoute
  ApiVisionExtractRoute: typeof ApiVisionExtractRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/templates': {
      id: '/api/templates'
      path: '/api/templates'
      fullPath: '/api/templates'
      preLoaderRoute: typeof ApiTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/samples': {
      id: '/api/samples'
      path: '/api/samples'
      fullPath: '/api/samples'
      preLoaderRoute: typeof ApiSamplesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/schemes': {
      id: '/_authenticated/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof AuthenticatedSchemesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/household': {
      id: '/_authenticated/household'
      path: '/household'
      fullPath: '/household'
      preLoaderRoute: typeof AuthenticatedHouseholdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/grievances': {
      id: '/_authenticated/grievances'
      path: '/grievances'
      fullPath: '/grievances'
      preLoaderRoute: typeof AuthenticatedGrievancesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/vision/extract': {
      id: '/api/vision/extract'
      path: '/api/vision/extract'
      fullPath: '/api/vision/extract'
      preLoaderRoute: typeof ApiVisionExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/session/export': {
      id: '/api/session/export'
      path: '/api/session/export'
      fullPath: '/api/session/export'
      preLoaderRoute: typeof ApiSessionExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grievance/draft': {
      id: '/api/grievance/draft'
      path: '/api/grievance/draft'
      fullPath: '/api/grievance/draft'
      preLoaderRoute: typeof ApiGrievanceDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bhashini/asr': {
      id: '/api/bhashini/asr'
      path: '/api/bhashini/asr'
      fullPath: '/api/bhashini/asr'
      preLoaderRoute: typeof ApiBhashiniAsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/turn': {
      id: '/api/agent/turn'
      path: '/api/agent/turn'
      fullPath: '/api/agent/turn'
      preLoaderRoute: typeof ApiAgentTurnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/stream': {
      id: '/api/agent/stream'
      path: '/api/agent/stream'
      fullPath: '/api/agent/stream'
      preLoaderRoute: typeof ApiAgentStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/resume': {
      id: '/api/agent/resume'
      path: '/api/agent/resume'
      fullPath: '/api/agent/resume'
      preLoaderRoute: typeof ApiAgentResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGrievancesRoute: typeof AuthenticatedGrievancesRoute
  AuthenticatedHouseholdRoute: typeof AuthenticatedHouseholdRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSchemesRoute: typeof AuthenticatedSchemesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGrievancesRoute: AuthenticatedGrievancesRoute,
  AuthenticatedHouseholdRoute: AuthenticatedHouseholdRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSchemesRoute: AuthenticatedSchemesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AppRoute: AppRoute,
  AuthRoute: AuthRoute,
  ImpactRoute: ImpactRoute,
  KioskRoute: KioskRoute,
  ApiSamplesRoute: ApiSamplesRoute,
  ApiTemplatesRoute: ApiTemplatesRoute,
  ApiAgentResumeRoute: ApiAgentResumeRoute,
  ApiAgentStreamRoute: ApiAgentStreamRoute,
  ApiAgentTurnRoute: ApiAgentTurnRoute,
  ApiBhashiniAsrRoute: ApiBhashiniAsrRoute,
  ApiGrievanceDraftRoute: ApiGrievanceDraftRoute,
  ApiSessionExportRoute: ApiSessionExportRoute,
  ApiVisionExtractRoute: ApiVisionExtractRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
